
name: Deploy to Firebase Hosting on Push to Main
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # These permissions are required by the 'firebase-hosting-deploy' action
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - run: npm i -g firebase-tools

      # The deploy action also needs credentials to act on your behalf
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          projectId: ${{ secrets.FB_PROJECT_ID }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GURURBRAHMA_SERVICES }}
          channelId: live
        env:
          # This experimental flag is needed for Next.js support
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          # These env vars are needed for the build step (server-side rendering)
          FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FB_CLIENT_EMAIL: ${{ secrets.FB_CLIENT_EMAIL }}
          FB_PRIVATE_KEY: ${{ secrets.FB_PRIVATE_KEY }}

    